<a href="https://colab.research.google.com/github/NgoThanhNha/Artificial_Intelligence/blob/main/Artificial_Neuron_Network_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]

In [ ]:
model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [ ]:
x1 = [[0.5,0],[0,0.5],[0.6,0],[0.51,0],[0,0.51],[10,-2],[-0.2,1]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)

[0 0 1 1 1 1 1]


1.0

In [ ]:
#--------------Example_2-----------------
from sklearn.linear_model import Perceptron
x1 = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y1 = [1,1,0,0]
model = Perceptron()
model.fit(x1,y1)
model.score(x1,y1)

1.0

In [ ]:
x2 = [[-0.5,0],[0,-0.5],[-0.4,0],[-0.6,0],[0,-0.51],[10,-2],[-0.2,1]]
y2 = model.predict(x2)
print(y2)

[1 1 1 1 1 0 0]


In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3) 
sc = StandardScaler()
sc.fit(X_train)
sc.fit(X_test)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [ ]:
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(y_test)
print(y_pred)
print('Độ chính xác khi chưa scale:',accuracy_score(y_test,y_pred))

[2 0 2 2 0 0 1 2 0 0 1 2 2 2 0 1 1 2 0 1 2 1 1 2 0 1 2 0 0 2 2 2 0 0 1 2 1
 2 1 0 2 1 0 0 0]
[1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1
 1 1 0 1 1 0 0 0]
Độ chính xác khi chưa scale: 0.6222222222222222


In [ ]:
#----------------------Đã Scale----------------------
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_test)
print(y_pred)
print('Độ chính xác khi đã scale:',accuracy_score(y_test,y_pred))

[2 0 2 2 0 0 1 2 0 0 1 2 2 2 0 1 1 2 0 1 2 1 1 2 0 1 2 0 0 2 2 2 0 0 1 2 1
 2 1 0 2 1 0 0 0]
[2 0 2 2 0 0 1 1 0 0 1 2 2 1 0 1 1 1 0 1 2 1 1 2 0 1 2 0 0 1 2 2 0 0 1 2 1
 2 1 0 2 1 0 0 0]
Độ chính xác khi đã scale: 0.9111111111111111


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import linear_model
url = "lung_cancer_examples.csv"
data = pd.read_csv(url)
data.head()

Age  Smokes  Result
0   35       3       1
1   27      20       1
2   30       0       0
3   28       0       0
4   68       4       1

In [ ]:
X = data.iloc[:, :-1].values 
y = data.iloc[:, -1].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3) 
sc = StandardScaler()
sc.fit(X_train)
sc.fit(X_test)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(y_test)
print(y_pred)
print('Độ chính xác khi chưa scale:',accuracy_score(y_test,y_pred))

[0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Độ chính xác khi chưa scale: 0.3888888888888889


In [ ]:
#----------------------Đã Scale----------------------
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_test)
print(y_pred)
print('Độ chính xác khi đã scale:',accuracy_score(y_test,y_pred))

[0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0]
[1 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0]
Độ chính xác khi đã scale: 0.8888888888888888
